"""Generate the readable markdown vault from the data files.

Everything written here is overwritten on each render. Hand edits go in vault/data/*.jsonl,
vault/taxonomy.md, or vault/feedback.md instead.
"""

import re
import shutil
from collections import defaultdict
from datetime import date

from . import config
from .store import Insight, Vault

GENERATED_DIRS = ["topics", "tools", "reels"]
HEADER = "<!-- Generated by `python -m doomscroll render`. Do not edit; see CLAUDE.md. -->\n"
LOW_CONFIDENCE = 0.6
STATUS_ORDER = ["investigating", "new", "tried", "adopted", "dropped"]
UNGROUPED = "Ungrouped"


def taxonomy_paths() -> set[str]:
    """Topic/category paths declared in taxonomy.md as list items like "- `system-design/caching`"."""
    if not config.TAXONOMY_FILE.exists():
        return set()
    return set(re.findall(r"^\s*-\s*`([^`]+)`", config.TAXONOMY_FILE.read_text(), re.MULTILINE))


ACRONYMS = {"api": "API", "ai": "AI", "ml": "ML", "sql": "SQL", "cdn": "CDN", "ci": "CI", "cd": "CD"}


def plural(n: int, word: str) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {word}s"


def title_case(slug: str) -> str:
    return " ".join(ACRONYMS.get(w, w.capitalize()) for w in slug.split("-"))


def _reel_link(vault: Vault, reel_id: str, depth: int) -> str:
    return f"[{reel_id}]({'../' * depth}reels/{reel_id}.md)"


def _count(ins: Insight) -> str:
    return f" (×{len(ins.sources)})" if len(ins.sources) > 1 else ""


def render_topic(vault: Vault, topic: str, insights: list[Insight]) -> str:
    depth = topic.count("/") + 1
    top = [i for i in insights if i.parent is None]
    children = defaultdict(list)
    for i in vault.insights.values():
        if i.parent:
            children[i.parent].append(i)

    reel_ids = {r for i in insights for r in i.sources}
    title = title_case(topic.split("/")[-1])
    lines = [HEADER, f"# {title}", f"_{plural(len(insights), 'insight')} from {plural(len(reel_ids), 'reel')} · `{topic}`_", ""]

    groups: dict[str | None, list[Insight]] = defaultdict(list)
    for i in top:
        groups[i.group].append(i)
    related = related_groups(vault, groups)

    def group_key(name):
        # Bigger groups first; Ungrouped (None) last.
        return (name is None, -sum(len(i.sources) for i in groups[name]))

    for name in sorted(groups, key=group_key):
        if name is None:
            lines += [f"## {UNGROUPED}", "", "_New arrivals. Sorted into groups weekly, or when you ask Claude._", ""]
        else:
            lines += [f"## {name}", ""]
            if related.get(name):
                lines += ["_See also: " + ", ".join(related[name]) + "_", ""]
        for ins in sorted(groups[name], key=lambda i: -len(i.sources)):
            sources = ", ".join(_reel_link(vault, r, depth) for r in ins.sources)
            lines.append(f"- **{ins.text}**{_count(ins)} · _{ins.kind}_ · {sources}")
            for child in sorted(children[ins.id], key=lambda i: -len(i.sources)):
                lines.append(f"  - Nuance: {child.text}{_count(child)}")
            for cid in ins.contradicts:
                if cid in vault.insights:
                    lines.append(f"  - ⚠️ Conflicts with: {vault.insights[cid].text}")
        lines.append("")
    return "\n".join(lines)


def related_groups(vault: Vault, groups: dict[str | None, list[Insight]]) -> dict[str, list[str]]:
    """Up to two "See also" links per group: other groups in the topic with similar centroids."""
    centroids = {name: vault.centroid([i.id for i in members if i.id in vault.vectors])
                 for name, members in groups.items()
                 if name is not None and any(i.id in vault.vectors for i in members)}
    related = {}
    for name, c in centroids.items():
        ranked = sorted(((float(c @ other), n) for n, other in centroids.items() if n != name), reverse=True)
        related[name] = [n for sim, n in ranked[:2] if sim >= config.RELATED_THRESHOLD]
    return related


def render_tool(vault: Vault, tool) -> str:
    lines = [
        HEADER,
        "---",
        f"name: {tool.name}",
        f"category: {tool.category}",
        f"status: {tool.status}",
        f"first_seen: {tool.first_seen}",
        f"mentions: {len(tool.sources)}",
        "---",
        f"# {tool.name}",
        "",
        tool.what_it_is,
        "",
    ]
    if tool.link:
        lines += [f"**Link:** {tool.link}", ""]
    lines += ["## What creators claimed", ""]
    for reel_id, claim in zip(tool.sources, tool.mentions):
        lines.append(f"- {claim} ({_reel_link(vault, reel_id, 1)})")
    if tool.notes:
        lines += ["", "## Investigation notes", "", tool.notes]
    return "\n".join(lines) + "\n"


def render_reel(reel) -> str:
    lines = [HEADER, f"# {reel.title}", "", f"**Source:** {reel.url} · **Author:** {reel.author} · **Saved:** {reel.processed}", ""]
    if reel.note:
        lines += [f"**Why I saved it:** {reel.note}", ""]
    lines += ["## Summary", "", reel.summary, "", "## Transcript", "", reel.transcript, ""]
    if reel.caption:
        lines += ["## Caption", "", reel.caption, ""]
    return "\n".join(lines)


def render_queue(vault: Vault) -> str:
    lines = [HEADER, "# Tool queue", ""]
    by_status = defaultdict(list)
    for t in vault.tools.values():
        by_status[t.status].append(t)
    for status in STATUS_ORDER + sorted(set(by_status) - set(STATUS_ORDER)):
        tools = sorted(by_status.get(status, []), key=lambda t: (-len(t.sources), t.name.lower()))
        if not tools:
            continue
        lines += [f"## {status.title()} ({len(tools)})", "", "| Tool | Category | Mentions | What it is |", "|---|---|---|---|"]
        for t in tools:
            lines.append(f"| [{t.name}](tools/{t.id}.md) | `{t.category}` | {len(t.sources)} | {t.what_it_is} |")
        lines.append("")
    return "\n".join(lines)


def render_inbox(vault: Vault) -> str:
    known = taxonomy_paths()
    lines = [HEADER, "# Inbox", "", "Items for Claude (or you) to review. See CLAUDE.md → Feedback workflow.", ""]

    low = [r for r in vault.reels.values() if r.confidence < LOW_CONFIDENCE]
    if low:
        lines += ["## Low-confidence reels", ""]
        lines += [f"- [{r.title}](reels/{r.id}.md) — confidence {r.confidence:.2f}" for r in low]
        lines.append("")

    used = {i.topic for i in vault.insights.values()} | {t.category for t in vault.tools.values()}
    proposed = sorted(used - known)
    if proposed:
        lines += ["## Paths not in taxonomy.md", "", "Approve (add to taxonomy.md) or remap them.", ""]
        lines += [f"- `{p}`" for p in proposed]
        lines.append("")

    ungrouped = defaultdict(int)
    for i in vault.insights.values():
        if i.parent is None and i.group is None:
            ungrouped[i.topic] += 1
    if ungrouped:
        lines += ["## Ungrouped insights", "", "Grouped by the weekly regroup, or ask Claude to group them now.", ""]
        lines += [f"- [{t}](topics/{t}.md): {n}" for t, n in sorted(ungrouped.items())]
        lines.append("")

    conflicts = [i for i in vault.insights.values() if i.contradicts]
    if conflicts:
        lines += ["## Unresolved conflicts", ""]
        lines += [f"- {i.text} (`{i.id}`, {i.topic})" for i in conflicts]
        lines.append("")

    if len(lines) == 5:
        lines.append("Nothing to review.")
    return "\n".join(lines) + "\n"


def render_index(vault: Vault) -> str:
    topics = defaultdict(int)
    for i in vault.insights.values():
        topics[i.topic] += 1
    lines = [
        HEADER,
        "# Doomscroll vault",
        f"_{plural(len(vault.reels), 'reel')} · {plural(len(vault.insights), 'insight')} · {plural(len(vault.tools), 'tool')} · rendered {date.today().isoformat()}_",
        "",
        "- [Tool queue](queue.md)",
        "- [Inbox](inbox.md)",
        "",
        "## Topics",
        "",
    ]
    lines += [f"- [{t}](topics/{t}.md) — {plural(n, 'insight')}" for t, n in sorted(topics.items())]
    return "\n".join(lines) + "\n"


def render_all(vault: Vault) -> None:
    for d in GENERATED_DIRS:
        shutil.rmtree(config.VAULT / d, ignore_errors=True)

    by_topic = defaultdict(list)
    for i in vault.insights.values():
        by_topic[i.topic].append(i)
    for topic, insights in by_topic.items():
        path = config.VAULT / "topics" / f"{topic}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_topic(vault, topic, insights))

    (config.VAULT / "tools").mkdir(parents=True, exist_ok=True)
    for tool in vault.tools.values():
        (config.VAULT / "tools" / f"{tool.id}.md").write_text(render_tool(vault, tool))

    (config.VAULT / "reels").mkdir(parents=True, exist_ok=True)
    for reel in vault.reels.values():
        (config.VAULT / "reels" / f"{reel.id}.md").write_text(render_reel(reel))

    (config.VAULT / "queue.md").write_text(render_queue(vault))
    (config.VAULT / "inbox.md").write_text(render_inbox(vault))
    (config.VAULT / "index.md").write_text(render_index(vault))
